image: php:7.1

before_script:
  - apt-get update -y
  - apt-get install -yq git
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer install --dev

stages:
  - deploy

phpcs:
  stage: deploy
  script:
    - echo "Start code sniffer..."
    - ./vendor/bin/phpcs src/
  when: always
  only:
    - code-review

phpcpd:
  stage: deploy
  script:
    - echo "Start copy/paste detector..."
    - ./vendor/bin/phpcpd src/
  when: always
  only:
    - code-review

