image: php:7.1

before_script:
  - apt-get update -y
  - apt-get install -yq git
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer install --dev

stages:
  - deploy

phpcs:
  stage: deploy
  script:
    - echo "Start code sniffer..."
    - ./vendor/bin/phpcs --standard=Zend  src/
  when: always
  only:
    - code-review

phpcpd:
  stage: deploy
  script:
    - echo "Start copy/paste detector..."
    - ./vendor/bin/phpcpd src/
  when: always
  only:
    - code-review

deploy_to_heroku:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=right-way --api-key=$HEROKU_STAGING_API_KEY
  when: manual
  only:
  - master


