image: php:7.1

before_script:
  - whoami
  - apt-get update -y
  - apt-get install git -y
  - curl -sS http://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer
  - composer install --no-plugins --no-scripts

stages:
  - deploy

phpcs:
  stage: deploy
  script:
    - echo "Start code sniffer..."
    - ./vendor/bin/phpcs src/
  when: always
  only:
    - code-review

phpcpd:
  stage: deploy
  script:
    - echo "Start copy/paste detector..."
    - ./vendor/bin/phpcpd src/
  when: always
  only:
    - code-review

